TS 2000에 오류 있음
- [공통]통계청 한국표준산업분류 코드 11차(중분류) = [공통]통계청 한국표준산업분류 코드 11차(대분류)
- 코드 말고 한글은 오류 없음

# 외감기업 (코스닥 + 코스피 + 비상장 외감기업)

In [41]:
import pandas as pd

cf1 = pd.read_excel('TS2000외감_2024(1).xlsx')
cf2 = pd.read_excel('TS2000외감_2024(2).xlsx')
cf3 = pd.read_excel('TS2000외감_2024(3).xlsx')

df = pd.concat([cf1,cf2,cf3], ignore_index=True)

In [54]:
df['[공통]통계청 한국표준산업분류 11차(대분류)'].value_counts()

[공통]통계청 한국표준산업분류 11차(대분류)
제조업                                  14676
부동산업                                  7471
도매 및 소매업                              5957
건설업                                   3171
정보통신업                                 1829
전문, 과학 및 기술 서비스업                      1688
운수 및 창고업                              1676
사업시설 관리, 사업 지원 및 임대 서비스업              1326
숙박 및 음식점업                              648
예술, 스포츠 및 여가관련 서비스업                    583
수도, 하수 및 폐기물 처리, 원료 재생업                476
전기, 가스, 증기 및 공기조절 공급업                  380
금융 및 보험업                               377
협회 및 단체, 수리 및 기타 개인 서비스업               243
농업, 임업 및 어업                            230
교육 서비스업                                149
광업                                      90
보건업 및 사회복지 서비스업                         32
공공 행정, 국방 및 사회보장 행정                      6
가구 내 고용활동 및 달리 분류되지 않은 자가 소비 생산활동        1
Name: count, dtype: int64

In [55]:
df['[공통]통계청 한국표준산업분류 11차(중분류)'].value_counts()

[공통]통계청 한국표준산업분류 11차(중분류)
부동산업                                      7471
도매 및 상품 중개업                               4437
기타 기계 및 장비 제조업                            2092
종합 건설업                                    2055
금속가공제품 제조업; 기계 및 가구 제외                    1373
                                          ...
임업                                           4
광업 지원 서비스업                                   4
담배 제조업                                       3
보험업                                          2
달리 분류되지 않은 자가소비를 위한 가구의 재화 및 서비스 생산활동        1
Name: count, Length: 75, dtype: int64

In [44]:
df.shape

(41009, 7)

In [45]:
df['[공통]통계청 한국표준산업분류 11차(대분류)'].value_counts()

[공통]통계청 한국표준산업분류 11차(대분류)
제조업                                  14676
부동산업                                  7471
도매 및 소매업                              5957
건설업                                   3171
정보통신업                                 1829
전문, 과학 및 기술 서비스업                      1688
운수 및 창고업                              1676
사업시설 관리, 사업 지원 및 임대 서비스업              1326
숙박 및 음식점업                              648
예술, 스포츠 및 여가관련 서비스업                    583
수도, 하수 및 폐기물 처리, 원료 재생업                476
전기, 가스, 증기 및 공기조절 공급업                  380
금융 및 보험업                               377
협회 및 단체, 수리 및 기타 개인 서비스업               243
농업, 임업 및 어업                            230
교육 서비스업                                149
광업                                      90
보건업 및 사회복지 서비스업                         32
공공 행정, 국방 및 사회보장 행정                      6
가구 내 고용활동 및 달리 분류되지 않은 자가 소비 생산활동        1
Name: count, dtype: int64

In [46]:
df.loc[
    df['[공통]통계청 한국표준산업분류 11차(대분류)'] == '제조업',
    '[공통]통계청 한국표준산업분류 11차(중분류)'
].value_counts()

[공통]통계청 한국표준산업분류 11차(중분류)
기타 기계 및 장비 제조업                   2092
금속가공제품 제조업; 기계 및 가구 제외           1373
자동차 및 트레일러 제조업                   1281
화학물질 및 화학제품 제조업; 의약품 제외          1193
식료품 제조업                          1158
전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업     1139
고무 및 플라스틱제품 제조업                   951
전기장비 제조업                          916
1차 금속 제조업                         860
비금속 광물제품 제조업                      651
의료, 정밀, 광학기기 및 시계 제조업             518
의복, 의복 액세서리 및 모피제품 제조업            411
섬유제품 제조업; 의복제외                    370
기타 운송장비 제조업                       351
펄프, 종이 및 종이제품 제조업                 251
의료용 물질 및 의약품 제조업                  233
기타 제품 제조업                         212
인쇄 및 기록매체 복제업                     173
가죽, 가방 및 신발 제조업                   123
가구 제조업                            119
목재 및 나무제품 제조업; 가구 제외              115
음료 제조업                             92
코크스, 연탄 및 석유정제품 제조업                50
산업용 기계 및 장비 수리업                    41
담배 제조업                              3
Name: count, dtype: int64

In [47]:
df['[공통]통계청 한국표준산업분류 11차(중분류)'].value_counts()

[공통]통계청 한국표준산업분류 11차(중분류)
부동산업                                      7471
도매 및 상품 중개업                               4437
기타 기계 및 장비 제조업                            2092
종합 건설업                                    2055
금속가공제품 제조업; 기계 및 가구 제외                    1373
                                          ...
임업                                           4
광업 지원 서비스업                                   4
담배 제조업                                       3
보험업                                          2
달리 분류되지 않은 자가소비를 위한 가구의 재화 및 서비스 생산활동        1
Name: count, Length: 75, dtype: int64

In [48]:
# 대분류 안에 각 고윳값(=대분류 섹터)의 비중 확인

( df['[공통]통계청 한국표준산업분류 11차(대분류)']
    .value_counts(normalize=True)
    * 100
).round(2)

[공통]통계청 한국표준산업분류 11차(대분류)
제조업                                  35.79
부동산업                                 18.22
도매 및 소매업                             14.53
건설업                                   7.73
정보통신업                                 4.46
전문, 과학 및 기술 서비스업                      4.12
운수 및 창고업                              4.09
사업시설 관리, 사업 지원 및 임대 서비스업              3.23
숙박 및 음식점업                             1.58
예술, 스포츠 및 여가관련 서비스업                   1.42
수도, 하수 및 폐기물 처리, 원료 재생업               1.16
전기, 가스, 증기 및 공기조절 공급업                 0.93
금융 및 보험업                              0.92
협회 및 단체, 수리 및 기타 개인 서비스업              0.59
농업, 임업 및 어업                           0.56
교육 서비스업                               0.36
광업                                    0.22
보건업 및 사회복지 서비스업                       0.08
공공 행정, 국방 및 사회보장 행정                   0.01
가구 내 고용활동 및 달리 분류되지 않은 자가 소비 생산활동     0.00
Name: proportion, dtype: float64

In [49]:
( df['[공통]통계청 한국표준산업분류 11차(중분류)']
    .value_counts(normalize=True)
    * 100
).round(2)

[공통]통계청 한국표준산업분류 11차(중분류)
부동산업                                      18.22
도매 및 상품 중개업                               10.82
기타 기계 및 장비 제조업                             5.10
종합 건설업                                     5.01
금속가공제품 제조업; 기계 및 가구 제외                     3.35
                                          ...
임업                                         0.01
광업 지원 서비스업                                 0.01
담배 제조업                                     0.01
보험업                                        0.00
달리 분류되지 않은 자가소비를 위한 가구의 재화 및 서비스 생산활동      0.00
Name: proportion, Length: 75, dtype: float64

In [50]:
result = (
    df.groupby(
        ['[공통]통계청 한국표준산업분류 11차(대분류)',
         '[공통]통계청 한국표준산업분류 11차(중분류)']
    )
    .size()
    .reset_index(name='중분류 기업수')
)


total_n = len(df)

# 중분류가 전체 데이터에서 차지하는 비중 (%)
result['중분류_전체비중(%)'] = (
    result['중분류 기업수'] / total_n * 100
).round(2)

# 대분류별 중분류 개수
result['대분류 안에 중분류개수'] = (
    result.groupby('[공통]통계청 한국표준산업분류 11차(대분류)')
    ['[공통]통계청 한국표준산업분류 11차(중분류)']
    .transform('nunique')
)


# 대분류 전체 기업수
result['대분류_전체기업수'] = (
    result.groupby('[공통]통계청 한국표준산업분류 11차(대분류)')['중분류 기업수']
    .transform('sum')
)

# 대분류 비중 (%)
result['대분류비중(%)'] = (
    result['대분류_전체기업수'] / total_n * 100
).round(2)


# 대분류 비중 큰 순으로 정렬
result = result.sort_values(
    by=['중분류 기업수'],
    ascending=False
)

result

,[공통]통계청 한국표준산업분류 11차(대분류),[공통]통계청 한국표준산업분류 11차(중분류),중분류 기업수,중분류_전체비중(%),대분류 안에 중분류개수,대분류_전체기업수,대분류비중(%)
20,부동산업,부동산업,7471,18.22,1,7471,18.22
15,도매 및 소매업,도매 및 상품 중개업,4437,10.82,3,5957,14.53
52,제조업,기타 기계 및 장비 제조업,2092,5.10,25,14676,35.79
2,건설업,종합 건설업,2055,5.01,2,3171,7.73
51,제조업,금속가공제품 제조업; 기계 및 가구 제외,1373,3.35,25,14676,35.79
...,...,...,...,...,...,...,...
4,광업,광업 지원 서비스업,4,0.01,4,90,0.22
14,"농업, 임업 및 어업",임업,4,0.01,3,230,0.56
55,제조업,담배 제조업,3,0.01,25,14676,35.79
11,금융 및 보험업,보험업,2,0.00,3,377,0.92
0,가구 내 고용활동 및 달리 분류되지 않은 자가 소비 생산활동,달리 분류되지 않은 자가소비를 위한 가구의 재화 및 서비스 생산활동,1,0.00,1,1,0.00

In [51]:
result.head(20)

,[공통]통계청 한국표준산업분류 11차(대분류),[공통]통계청 한국표준산업분류 11차(중분류),중분류 기업수,중분류_전체비중(%),대분류 안에 중분류개수,대분류_전체기업수,대분류비중(%)
20,부동산업,부동산업,7471,18.22,1,7471,18.22
15,도매 및 소매업,도매 및 상품 중개업,4437,10.82,3,5957,14.53
52,제조업,기타 기계 및 장비 제조업,2092,5.10,25,14676,35.79
2,건설업,종합 건설업,2055,5.01,2,3171,7.73
51,제조업,금속가공제품 제조업; 기계 및 가구 제외,1373,3.35,25,14676,35.79
66,제조업,자동차 및 트레일러 제조업,1281,3.12,25,14676,35.79
71,제조업,화학물질 및 화학제품 제조업; 의약품 제외,1193,2.91,25,14676,35.79
16,도매 및 소매업,소매업; 자동차 제외,1184,2.89,3,5957,14.53
60,제조업,식료품 제조업,1158,2.82,25,14676,35.79
68,제조업,"전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",1139,2.78,25,14676,35.79
1,건설업,전문직별 공사업,1116,2.72,2,3171,7.73
50,제조업,고무 및 플라스틱제품 제조업,951,2.32,25,14676,35.79
45,정보통신업,출판업,930,2.27,6,1829,4.46
67,제조업,전기장비 제조업,916,2.23,25,14676,35.79
34,운수 및 창고업,창고 및 운송관련 서비스업,887,2.16,4,1676,4.09
47,제조업,1차 금속 제조업,860,2.10,25,14676,35.79
40,"전문, 과학 및 기술 서비스업",전문 서비스업,851,2.08,4,1688,4.12
22,"사업시설 관리, 사업 지원 및 임대 서비스업",사업지원 서비스업,664,1.62,3,1326,3.23
57,제조업,비금속 광물제품 제조업,651,1.59,25,14676,35.79
33,운수 및 창고업,육상운송 및 파이프라인 운송업,548,1.34,4,1676,4.09

# 전체비중이 2% 넘는 중분류에 대해서 분석시 (17개 분류로 나뉘어진다)

In [52]:
result.loc[
    result['중분류_전체비중(%)'] >= 2,
    [
        '[공통]통계청 한국표준산업분류 11차(대분류)',
        '[공통]통계청 한국표준산업분류 11차(중분류)',
        '중분류_전체비중(%)'
    ]
]

   [공통]통계청 한국표준산업분류 11차(대분류)      [공통]통계청 한국표준산업분류 11차(중분류)  중분류_전체비중(%)
20                      부동산업                          부동산업         18.22
15                  도매 및 소매업                   도매 및 상품 중개업         10.82
52                       제조업                기타 기계 및 장비 제조업          5.10
2                        건설업                        종합 건설업          5.01
51                       제조업        금속가공제품 제조업; 기계 및 가구 제외          3.35
66                       제조업                자동차 및 트레일러 제조업          3.12
71                       제조업       화학물질 및 화학제품 제조업; 의약품 제외          2.91
16                  도매 및 소매업                   소매업; 자동차 제외          2.89
60                       제조업                       식료품 제조업          2.82
68                       제조업  전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업          2.78
1                        건설업                      전문직별 공사업          2.72
50                       제조업               고무 및 플라스틱제품 제조업          2.32
45                     정보통신업                           출판업          2.27
67                       제조업                      전기장비 제조업          2.23
34                  운수 및 창고업                창고 및 운송관련 서비스업          2.16
47                       제조업                     1차 금속 제조업          2.10
40          전문, 과학 및 기술 서비스업                       전문 서비스업          2.08

In [53]:
# 이경우 비상장외감기업 + 코스닥 상장기업의 72%를 분석할 수 있다
result.loc[
    result['중분류_전체비중(%)'] >= 2,
    '중분류_전체비중(%)'
].sum()

np.float64(72.89999999999999)

In [56]:
df.shape

(41009, 7)