# 코스닥

In [1]:
import pandas as pd

df = pd.read_excel('TS2000코스닥_2024.xlsx')

In [2]:
df['[공통]통계청 한국표준산업분류 11차(중분류)'].value_counts()

[공통]통계청 한국표준산업분류 11차(중분류)
전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업     250
기타 기계 및 장비 제조업                   184
출판업                              179
의료용 물질 및 의약품 제조업                 132
의료, 정밀, 광학기기 및 시계 제조업             99
화학물질 및 화학제품 제조업; 의약품 제외           97
도매 및 상품 중개업                       77
전기장비 제조업                          65
연구개발업                             65
자동차 및 트레일러 제조업                    58
식료품 제조업                           42
금속가공제품 제조업; 기계 및 가구 제외            41
전문 서비스업                           36
1차 금속 제조업                         34
영상ㆍ오디오 기록물 제작 및 배급업               33
고무 및 플라스틱제품 제조업                   30
컴퓨터 프로그래밍, 시스템 통합 및 관리업           30
정보서비스업                            24
소매업; 자동차 제외                       22
기타 운송장비 제조업                       19
기타 전문, 과학 및 기술 서비스업               18
종합 건설업                            17
비금속 광물제품 제조업                      15
의복, 의복 액세서리 및 모피제품 제조업            15
건축기술, 엔지니어링 및 기타 과학기술 서비스업        13
기타 제품 제조업                         12
전문직별 공사업                          11
사업지원 서비스업                         11
우편 및 통신업                           9
방송 및 영상·오디오물 제공 서비스업               9
교육 서비스업                            9
펄프, 종이 및 종이제품 제조업                  8
창작, 예술 및 여가관련 서비스업                 6
음료 제조업                             6
섬유제품 제조업; 의복제외                     5
금융 및 보험 관련 서비스업                    4
자동차 및 부품 판매업                       4
부동산업                               4
가구 제조업                             3
전기, 가스, 증기 및 공기조절 공급업              3
폐기물 수집, 운반, 처리 및 원료 재생업            3
금융업                                3
숙박업                                2
가죽, 가방 및 신발 제조업                    2
인쇄 및 기록매체 복제업                      2
창고 및 운송관련 서비스업                     2
육상운송 및 파이프라인 운송업                   2
목재 및 나무제품 제조업; 가구 제외               2
농업                                 2
개인 및 소비용품 수리업                      1
스포츠 및 오락관련 서비스업                    1
사업시설 관리 및 조경 서비스업                  1
Name: count, dtype: int64

In [3]:
df['[공통]통계청 한국표준산업분류 11차(대분류)'].value_counts()

[공통]통계청 한국표준산업분류 11차(대분류)
제조업                         1121
정보통신업                        284
전문, 과학 및 기술 서비스업             132
도매 및 소매업                     103
건설업                           28
사업시설 관리, 사업 지원 및 임대 서비스업      12
교육 서비스업                        9
예술, 스포츠 및 여가관련 서비스업            7
금융 및 보험업                       7
운수 및 창고업                       4
부동산업                           4
전기, 가스, 증기 및 공기조절 공급업          3
수도, 하수 및 폐기물 처리, 원료 재생업        3
숙박 및 음식점업                      2
농업, 임업 및 어업                    2
협회 및 단체, 수리 및 기타 개인 서비스업       1
Name: count, dtype: int64

In [4]:
df['[공통]통계청 한국표준산업분류 코드 11차(대분류)'].value_counts()

[공통]통계청 한국표준산업분류 코드 11차(대분류)
26    250
29    184
58    179
21    132
27     99
20     97
46     77
28     65
70     65
30     58
10     42
25     41
71     36
24     34
59     33
22     30
62     30
63     24
47     22
31     19
73     18
41     17
23     15
14     15
72     13
33     12
42     11
75     11
61      9
60      9
85      9
17      8
90      6
11      6
13      5
66      4
45      4
68      4
32      3
35      3
38      3
64      3
55      2
15      2
18      2
52      2
49      2
16      2
1       2
95      1
91      1
74      1
Name: count, dtype: int64

In [5]:
df['[공통]통계청 한국표준산업분류 코드 11차(중분류)'].value_counts()

[공통]통계청 한국표준산업분류 코드 11차(중분류)
26    250
29    184
58    179
21    132
27     99
20     97
46     77
28     65
70     65
30     58
10     42
25     41
71     36
24     34
59     33
22     30
62     30
63     24
47     22
31     19
73     18
41     17
23     15
14     15
72     13
33     12
42     11
75     11
61      9
60      9
85      9
17      8
90      6
11      6
13      5
66      4
45      4
68      4
32      3
35      3
38      3
64      3
55      2
15      2
18      2
52      2
49      2
16      2
1       2
95      1
91      1
74      1
Name: count, dtype: int64

TS 2000에 오류 있음
- [공통]통계청 한국표준산업분류 코드 11차(중분류) = [공통]통계청 한국표준산업분류 코드 11차(대분류)
- 코드 말고 한글은 오류 없음

In [3]:
df.shape

(1722, 7)

# 외감기업

In [5]:
import pandas as pd

cf1 = pd.read_excel('TS2000외감_2024(1).xlsx')
cf2 = pd.read_excel('TS2000외감_2024(2).xlsx')
cf3 = pd.read_excel('TS2000외감_2024(3).xlsx')

cf = pd.concat([cf1,cf2,cf3], ignore_index=True)

In [13]:
cf['[공통]통계청 한국표준산업분류 11차(대분류)'].value_counts()

[공통]통계청 한국표준산업분류 11차(대분류)
제조업                                  14676
부동산업                                  7471
도매 및 소매업                              5957
건설업                                   3171
정보통신업                                 1829
전문, 과학 및 기술 서비스업                      1688
운수 및 창고업                              1676
사업시설 관리, 사업 지원 및 임대 서비스업              1326
숙박 및 음식점업                              648
예술, 스포츠 및 여가관련 서비스업                    583
수도, 하수 및 폐기물 처리, 원료 재생업                476
전기, 가스, 증기 및 공기조절 공급업                  380
금융 및 보험업                               377
협회 및 단체, 수리 및 기타 개인 서비스업               243
농업, 임업 및 어업                            230
교육 서비스업                                149
광업                                      90
보건업 및 사회복지 서비스업                         32
공공 행정, 국방 및 사회보장 행정                      6
가구 내 고용활동 및 달리 분류되지 않은 자가 소비 생산활동        1
Name: count, dtype: int64

In [14]:
cf['[공통]통계청 한국표준산업분류 11차(중분류)'].value_counts()

[공통]통계청 한국표준산업분류 11차(중분류)
부동산업                                      7471
도매 및 상품 중개업                               4437
기타 기계 및 장비 제조업                            2092
종합 건설업                                    2055
금속가공제품 제조업; 기계 및 가구 제외                    1373
                                          ...
임업                                           4
광업 지원 서비스업                                   4
담배 제조업                                       3
보험업                                          2
달리 분류되지 않은 자가소비를 위한 가구의 재화 및 서비스 생산활동        1
Name: count, Length: 75, dtype: int64

# 코스닥 + 외감기업

In [6]:
df = pd.concat([cf,df], ignore_index=True)

In [7]:
df.shape

(42731, 7)

In [ ]:
df['[공통]통계청 한국표준산업분류 11차(대분류)'].value_counts()

[공통]통계청 한국표준산업분류 11차(대분류)
제조업                                  15797
부동산업                                  7475
도매 및 소매업                              6060
건설업                                   3199
정보통신업                                 2113
전문, 과학 및 기술 서비스업                      1820
운수 및 창고업                              1680
사업시설 관리, 사업 지원 및 임대 서비스업              1338
숙박 및 음식점업                              650
예술, 스포츠 및 여가관련 서비스업                    590
수도, 하수 및 폐기물 처리, 원료 재생업                479
금융 및 보험업                               384
전기, 가스, 증기 및 공기조절 공급업                  383
협회 및 단체, 수리 및 기타 개인 서비스업               244
농업, 임업 및 어업                            232
교육 서비스업                                158
광업                                      90
보건업 및 사회복지 서비스업                         32
공공 행정, 국방 및 사회보장 행정                      6
가구 내 고용활동 및 달리 분류되지 않은 자가 소비 생산활동        1
Name: count, dtype: int64

In [11]:
df.loc[
    df['[공통]통계청 한국표준산업분류 11차(대분류)'] == '제조업',
    '[공통]통계청 한국표준산업분류 11차(중분류)'
].value_counts()

[공통]통계청 한국표준산업분류 11차(중분류)
기타 기계 및 장비 제조업                   2276
금속가공제품 제조업; 기계 및 가구 제외           1414
전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업     1389
자동차 및 트레일러 제조업                   1339
화학물질 및 화학제품 제조업; 의약품 제외          1290
식료품 제조업                          1200
고무 및 플라스틱제품 제조업                   981
전기장비 제조업                          981
1차 금속 제조업                         894
비금속 광물제품 제조업                      666
의료, 정밀, 광학기기 및 시계 제조업             617
의복, 의복 액세서리 및 모피제품 제조업            426
섬유제품 제조업; 의복제외                    375
기타 운송장비 제조업                       370
의료용 물질 및 의약품 제조업                  365
펄프, 종이 및 종이제품 제조업                 259
기타 제품 제조업                         224
인쇄 및 기록매체 복제업                     175
가죽, 가방 및 신발 제조업                   125
가구 제조업                            122
목재 및 나무제품 제조업; 가구 제외              117
음료 제조업                             98
코크스, 연탄 및 석유정제품 제조업                50
산업용 기계 및 장비 수리업                    41
담배 제조업                              3
Name: count, dtype: int64

In [10]:
df['[공통]통계청 한국표준산업분류 11차(중분류)'].value_counts()

[공통]통계청 한국표준산업분류 11차(중분류)
부동산업                                      7475
도매 및 상품 중개업                               4514
기타 기계 및 장비 제조업                            2276
종합 건설업                                    2072
금속가공제품 제조업; 기계 및 가구 제외                    1414
                                          ...
임업                                           4
광업 지원 서비스업                                   4
담배 제조업                                       3
보험업                                          2
달리 분류되지 않은 자가소비를 위한 가구의 재화 및 서비스 생산활동        1
Name: count, Length: 75, dtype: int64

In [ ]:
# 대분류 안에 각 고윳값(=대분류 섹터)의 비중 확인

( df['[공통]통계청 한국표준산업분류 11차(대분류)']
    .value_counts(normalize=True)
    * 100
).round(2)

[공통]통계청 한국표준산업분류 11차(대분류)
제조업                                  36.97
부동산업                                 17.49
도매 및 소매업                             14.18
건설업                                   7.49
정보통신업                                 4.94
전문, 과학 및 기술 서비스업                      4.26
운수 및 창고업                              3.93
사업시설 관리, 사업 지원 및 임대 서비스업              3.13
숙박 및 음식점업                             1.52
예술, 스포츠 및 여가관련 서비스업                   1.38
수도, 하수 및 폐기물 처리, 원료 재생업               1.12
금융 및 보험업                              0.90
전기, 가스, 증기 및 공기조절 공급업                 0.90
협회 및 단체, 수리 및 기타 개인 서비스업              0.57
농업, 임업 및 어업                           0.54
교육 서비스업                               0.37
광업                                    0.21
보건업 및 사회복지 서비스업                       0.07
공공 행정, 국방 및 사회보장 행정                   0.01
가구 내 고용활동 및 달리 분류되지 않은 자가 소비 생산활동     0.00
Name: proportion, dtype: float64

In [15]:
( df['[공통]통계청 한국표준산업분류 11차(중분류)']
    .value_counts(normalize=True)
    * 100
).round(2)

[공통]통계청 한국표준산업분류 11차(중분류)
부동산업                                      17.49
도매 및 상품 중개업                               10.56
기타 기계 및 장비 제조업                             5.33
종합 건설업                                     4.85
금속가공제품 제조업; 기계 및 가구 제외                     3.31
                                          ...
임업                                         0.01
광업 지원 서비스업                                 0.01
담배 제조업                                     0.01
보험업                                        0.00
달리 분류되지 않은 자가소비를 위한 가구의 재화 및 서비스 생산활동      0.00
Name: proportion, Length: 75, dtype: float64

In [29]:
result = (
    df.groupby(
        ['[공통]통계청 한국표준산업분류 11차(대분류)',
         '[공통]통계청 한국표준산업분류 11차(중분류)']
    )
    .size()
    .reset_index(name='중분류 기업수')
)


total_n = len(df)

# 중분류가 전체 데이터에서 차지하는 비중 (%)
result['중분류_전체비중(%)'] = (
    result['중분류 기업수'] / total_n * 100
).round(2)

# 대분류별 중분류 개수
result['대분류 안에 중분류개수'] = (
    result.groupby('[공통]통계청 한국표준산업분류 11차(대분류)')
    ['[공통]통계청 한국표준산업분류 11차(중분류)']
    .transform('nunique')
)


# 대분류 전체 기업수
result['대분류_전체기업수'] = (
    result.groupby('[공통]통계청 한국표준산업분류 11차(대분류)')['중분류 기업수']
    .transform('sum')
)

# 대분류 비중 (%)
result['대분류비중(%)'] = (
    result['대분류_전체기업수'] / total_n * 100
).round(2)


# 대분류 비중 큰 순으로 정렬
result = result.sort_values(
    by=['중분류 기업수'],
    ascending=False
)

result

,[공통]통계청 한국표준산업분류 11차(대분류),[공통]통계청 한국표준산업분류 11차(중분류),중분류 기업수,중분류_전체비중(%),대분류 안에 중분류개수,대분류_전체기업수,대분류비중(%)
20,부동산업,부동산업,7475,17.49,1,7475,17.49
15,도매 및 소매업,도매 및 상품 중개업,4514,10.56,3,6060,14.18
52,제조업,기타 기계 및 장비 제조업,2276,5.33,25,15797,36.97
2,건설업,종합 건설업,2072,4.85,2,3199,7.49
51,제조업,금속가공제품 제조업; 기계 및 가구 제외,1414,3.31,25,15797,36.97
...,...,...,...,...,...,...,...
4,광업,광업 지원 서비스업,4,0.01,4,90,0.21
14,"농업, 임업 및 어업",임업,4,0.01,3,232,0.54
55,제조업,담배 제조업,3,0.01,25,15797,36.97
11,금융 및 보험업,보험업,2,0.00,3,384,0.90
0,가구 내 고용활동 및 달리 분류되지 않은 자가 소비 생산활동,달리 분류되지 않은 자가소비를 위한 가구의 재화 및 서비스 생산활동,1,0.00,1,1,0.00

In [31]:
result.head(20)

,[공통]통계청 한국표준산업분류 11차(대분류),[공통]통계청 한국표준산업분류 11차(중분류),중분류 기업수,중분류_전체비중(%),대분류 안에 중분류개수,대분류_전체기업수,대분류비중(%)
20,부동산업,부동산업,7475,17.49,1,7475,17.49
15,도매 및 소매업,도매 및 상품 중개업,4514,10.56,3,6060,14.18
52,제조업,기타 기계 및 장비 제조업,2276,5.33,25,15797,36.97
2,건설업,종합 건설업,2072,4.85,2,3199,7.49
51,제조업,금속가공제품 제조업; 기계 및 가구 제외,1414,3.31,25,15797,36.97
68,제조업,"전자부품, 컴퓨터, 영상, 음향 및 통신장비 제조업",1389,3.25,25,15797,36.97
66,제조업,자동차 및 트레일러 제조업,1339,3.13,25,15797,36.97
71,제조업,화학물질 및 화학제품 제조업; 의약품 제외,1290,3.02,25,15797,36.97
16,도매 및 소매업,소매업; 자동차 제외,1206,2.82,3,6060,14.18
60,제조업,식료품 제조업,1200,2.81,25,15797,36.97
1,건설업,전문직별 공사업,1127,2.64,2,3199,7.49
45,정보통신업,출판업,1109,2.60,6,2113,4.94
50,제조업,고무 및 플라스틱제품 제조업,981,2.30,25,15797,36.97
67,제조업,전기장비 제조업,981,2.30,25,15797,36.97
47,제조업,1차 금속 제조업,894,2.09,25,15797,36.97
34,운수 및 창고업,창고 및 운송관련 서비스업,889,2.08,4,1680,3.93
40,"전문, 과학 및 기술 서비스업",전문 서비스업,887,2.08,4,1820,4.26
22,"사업시설 관리, 사업 지원 및 임대 서비스업",사업지원 서비스업,675,1.58,3,1338,3.13
57,제조업,비금속 광물제품 제조업,666,1.56,25,15797,36.97
62,제조업,"의료, 정밀, 광학기기 및 시계 제조업",617,1.44,25,15797,36.97