In [10]:
import pandas as pd

df = pd.read_excel('거시지표 4가지!.xlsx')

df.head()

,항목명1,단위,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,한국은행 기준금리,연%,2.500,3.250,2.750,2.500,2.000,1.500,1.250,1.500,1.750,1.250,0.500,1.000,3.250,3.500,3.000
1,소비자물가지수,2020=100,86.373,89.850,91.815,93.010,94.196,94.861,95.783,97.645,99.086,99.466,100.000,102.500,107.720,111.590,114.180
2,"국내총생산(명목, 원화표시)",십억원,"1,379,460.200","1,448,575.600","1,504,674.100","1,570,938.200","1,638,484.800","1,740,776.000","1,833,026.600","1,934,233.900","2,006,974.500","2,040,594.300","2,058,466.500","2,221,912.900","2,323,781.500","2,408,687.400","2,556,857.400"
3,국고채(3년),연%,3.720,3.620,3.130,2.790,2.589,1.794,1.442,1.801,2.099,1.529,0.988,1.392,3.199,3.573,3.107
4,"회사채(3년, AA-)",연%,4.660,4.410,3.770,3.190,2.983,2.084,1.886,2.325,2.651,2.023,2.128,2.083,4.155,4.394,3.676

In [11]:
df.T

,0,1,2,3,4,5
항목명1,한국은행 기준금리,소비자물가지수,"국내총생산(명목, 원화표시)",국고채(3년),"회사채(3년, AA-)","회사채(3년, BBB-)"
단위,연%,2020=100,십억원,연%,연%,연%
2010,2.500,86.373,"1,379,460.200",3.720,4.660,10.680
2011,3.250,89.850,"1,448,575.600",3.620,4.410,10.380
2012,2.750,91.815,"1,504,674.100",3.130,3.770,9.340
2013,2.500,93.010,"1,570,938.200",2.790,3.190,8.840
2014,2.000,94.196,"1,638,484.800",2.589,2.983,8.709
2015,1.500,94.861,"1,740,776.000",1.794,2.084,7.997
2016,1.250,95.783,"1,833,026.600",1.442,1.886,7.929
2017,1.500,97.645,"1,934,233.900",1.801,2.325,8.554
2018,1.750,99.086,"2,006,974.500",2.099,2.651,8.819
2019,1.250,99.466,"2,040,594.300",1.529,2.023,8.115
2020,0.500,100.000,"2,058,466.500",0.988,2.128,8.410
2021,1.000,102.500,"2,221,912.900",1.392,2.083,8.329
2022,3.250,107.720,"2,323,781.500",3.199,4.155,10.006
2023,3.500,111.590,"2,408,687.400",3.573,4.394,10.768
2024,3.000,114.180,"2,556,857.400",3.107,3.676,9.760

In [12]:
df = df.set_index(df.columns[0])

In [13]:
df

,단위,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
항목명1,,,,,,,,,,,,,,,,
한국은행 기준금리,연%,2.500,3.250,2.750,2.500,2.000,1.500,1.250,1.500,1.750,1.250,0.500,1.000,3.250,3.500,3.000
소비자물가지수,2020=100,86.373,89.850,91.815,93.010,94.196,94.861,95.783,97.645,99.086,99.466,100.000,102.500,107.720,111.590,114.180
"국내총생산(명목, 원화표시)",십억원,"1,379,460.200","1,448,575.600","1,504,674.100","1,570,938.200","1,638,484.800","1,740,776.000","1,833,026.600","1,934,233.900","2,006,974.500","2,040,594.300","2,058,466.500","2,221,912.900","2,323,781.500","2,408,687.400","2,556,857.400"
국고채(3년),연%,3.720,3.620,3.130,2.790,2.589,1.794,1.442,1.801,2.099,1.529,0.988,1.392,3.199,3.573,3.107
"회사채(3년, AA-)",연%,4.660,4.410,3.770,3.190,2.983,2.084,1.886,2.325,2.651,2.023,2.128,2.083,4.155,4.394,3.676
"회사채(3년, BBB-)",연%,10.680,10.380,9.340,8.840,8.709,7.997,7.929,8.554,8.819,8.115,8.410,8.329,10.006,10.768,9.760